# Generated by Django 5.2 on 2025-04-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referralhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='referralhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
