# Generated by Django 5.2 on 2025-05-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pairing_payment_status_alter_pairing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='investment',
        ),
    ]
